import Link from "next/link";
import { Navbar } from "./components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <div className="flex justify-center items-center p-5 gap-10 rounded-2xl shadow-lg w-fit absolute z-50 bg-white left-[50%] translate-x-[-50%]">
          {/* <Link href={"#"}>Logo</Link> */}
          <Navbar />
        </div>

        <main>{children}</main>
      </body>
    </html>
  );
}
